# Generated by Django 2.2.3 on 2019-07-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='pic_url',
            field=models.CharField(max_length=2000),
        ),
    ]
