# Generated by Django 2.2.3 on 2019-07-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190725_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='maps',
            field=models.TextField(help_text='Only insert src script from html embed', max_length=500),
        ),
    ]
